# Generated by Django 2.0.5 on 2018-05-26 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Elements_img')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('moderated', models.NullBooleanField(default=None)),
            ],
            options={
                'verbose_name': 'Элементы',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Groups_img')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('parrent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='mainapp.Groups')),
            ],
            options={
                'verbose_name': 'Группы',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AddField(
            model_name='elements',
            name='parrent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroupselement', to='mainapp.Groups'),
        ),
    ]
