# Generated by Django 2.0.5 on 2018-05-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='elements',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='elements',
            name='image',
            field=models.ImageField(upload_to='Elements_img', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='elements',
            name='moderated',
            field=models.NullBooleanField(default=None, verbose_name='Проверен модератором'),
        ),
        migrations.AlterField(
            model_name='elements',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='elements',
            name='parrent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroupselement', to='mainapp.Groups', verbose_name='Родительская группа'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='image',
            field=models.ImageField(upload_to='Groups_img', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='parrent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='mainapp.Groups', verbose_name='Родительская группа'),
        ),
    ]
