# Generated by Django 2.0.5 on 2018-05-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180527_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='description',
            field=models.TextField(blank=True, default=0, max_length=512, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groups',
            name='description',
            field=models.TextField(blank=True, default=0, max_length=512, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
