# Generated by Django 2.0.5 on 2019-09-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180531_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elements',
            old_name='parrent_group',
            new_name='group',
        ),
    ]
