# Generated by Django 2.0.5 on 2019-09-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190924_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='parrent_group',
            new_name='parent_group',
        ),
        migrations.AlterField(
            model_name='elements',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroupselement', to='mainapp.Groups', verbose_name='Группа'),
        ),
    ]
